# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813aa20eb19137e797719821ac01a68b9cd2a316ac7c72755306416a47ab8b879e5bea9478489abb2d2804108075bf242b2780f8b77f96b829772e2b19785fca

test:
  secret_key_base: f97f5c7e38921c5dee303d5954560e6224165d60c7d8e98b604724843bb49f80d1de252e5ff701a3c07f67100743964ecebfe7be75704c4be05b0b5aa46cbce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
