# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c23222c5fcf50e76b15010f5fdf84e73b80f4a30656898b99eb0252bbed0602659ec2877f4827d58cc6f05c1b5d2cf1d5678575e935577497934c984e74894de

test:
  secret_key_base: 79a49f0831bc326ec1562be95050b545211fcf9fd6bb06d50c6a4028eb9afc3e3c657abad7c9ba9245f1d66578d6ade3f4396601663fb59c63f1dc9884ad3c5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
