source 'https://rubygems.org'

gem 'rails',                '4.2.0.rc2'
gem 'sass-rails',           '5.0.0.beta1'
gem 'uglifier',             '2.5.3'
gem 'coffee-rails',         '4.1.0'
gem 'jquery-rails',         '4.0.0.beta2'
gem 'jbuilder',             '2.2.3'
gem 'bower-rails'
gem 'foreman'
gem 'angular-rails-templates'
gem 'pg',                   '0.17.1'
gem 'sdoc',                 '0.4.0', group: :doc

group :development, :test do
  gem 'byebug',      '3.4.0'
  gem 'web-console', '2.0.0.beta3'
  gem 'spring',      '1.1.3'
  gem "rspec-rails", "~> 2.0"
  gem "factory_girl_rails", "~> 4.0"
  gem "capybara"
  gem "database_cleaner"
  gem "selenium-webdriver"
  gem 'teaspoon'
  gem 'phantomjs'
end

group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
end

group :production do
  gem 'rails_12factor', '0.0.2'
  gem "rails_stdout_logging"
  gem "rails_serve_static_assets"
end

